name = "com2000-api"
main = "src/index-simple.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Worker settings
workers_dev = true

# Workers AI
ai = { binding = "AI" }

# Analytics Engine (disabled for initial deployment)
# analytics_engine_datasets = [
#   { binding = "ANALYTICS", dataset = "com2000_analytics" }
# ]

# KV Namespaces
kv_namespaces = [
  { binding = "SESSION_STORE", id = "48373b1d7ee74ebfa08f472ae35b76c7", preview_id = "48373b1d7ee74ebfa08f472ae35b76c7" },
  { binding = "PROJECT_CACHE", id = "f46cbe4170cc4287b60b994c795b24b6", preview_id = "f46cbe4170cc4287b60b994c795b24b6" },
  { binding = "RATE_LIMITER", id = "a1c4de99e2014e54a95e143811dc1e36", preview_id = "a1c4de99e2014e54a95e143811dc1e36" }
]

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "com2000-db"
database_id = "9a00518d-1d8c-4184-bf13-c037cd72117e"
migrations_dir = "migrations"

# R2 Buckets
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "com2000-assets"
preview_bucket_name = "com2000-assets-preview"

# Durable Objects (disabled for initial deployment)
# [[durable_objects.bindings]]
# name = "PRICE_UPDATER"
# class_name = "PriceUpdater"
# script_name = "com2000-price-sync"

# [[durable_objects.bindings]]
# name = "PROJECT_SYNC"
# class_name = "ProjectSync"
# script_name = "com2000-project-sync"

# Environment Variables
[vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0-dev"
JWT_SECRET = "dev-jwt-secret-change-in-production"
ENCRYPTION_KEY = "dev-encryption-key-change-in-production"
CORS_ORIGINS = "http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "900"
SESSION_TIMEOUT = "3600"
MAX_FILE_SIZE = "1048576"
CACHE_TTL = "10"

# Cron Triggers (disabled for initial deployment)
# [triggers]
# crons = [
#   "*/5 * * * *",  # Every 5 minutes
#   "0 0 * * *"     # Daily at midnight
# ]

# Staging Environment
[env.staging]
name = "com2000-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "1.0.0-staging"
JWT_SECRET = "your-staging-jwt-secret-here"
ENCRYPTION_KEY = "your-staging-encryption-key-here"
CORS_ORIGINS = "https://staging.com2000.org,http://localhost:3000"
RATE_LIMIT_REQUESTS = "500"
RATE_LIMIT_WINDOW = "900"
SESSION_TIMEOUT = "43200"
MAX_FILE_SIZE = "5242880"
CACHE_TTL = "60"

[[env.staging.kv_namespaces]]
binding = "SESSION_STORE"
id = "user_sessions_kv_staging"
preview_id = "user_sessions_kv_staging_preview"

[[env.staging.kv_namespaces]]
binding = "PROJECT_CACHE"
id = "project_cache_kv_staging"
preview_id = "project_cache_kv_staging_preview"

[[env.staging.kv_namespaces]]
binding = "RATE_LIMITER"
id = "rate_limiter_kv_staging"
preview_id = "rate_limiter_kv_staging_preview"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "com2000-db-staging"
database_id = "com2000_db_staging_id"

[[env.staging.r2_buckets]]
binding = "ASSETS"
bucket_name = "com2000-assets-staging"

# Production Environment
[env.production]
name = "com2000-api-production"

[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
JWT_SECRET = "your-production-jwt-secret-here"
ENCRYPTION_KEY = "your-production-encryption-key-here"
CORS_ORIGINS = "https://com2000.org,https://app.com2000.org"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "900"
SESSION_TIMEOUT = "86400"
MAX_FILE_SIZE = "10485760"
CACHE_TTL = "300"

[[env.production.kv_namespaces]]
binding = "SESSION_STORE"
id = "user_sessions_kv_production"
preview_id = "user_sessions_kv_production_preview"

[[env.production.kv_namespaces]]
binding = "PROJECT_CACHE"
id = "project_cache_kv_production"
preview_id = "project_cache_kv_production_preview"

[[env.production.kv_namespaces]]
binding = "RATE_LIMITER"
id = "rate_limiter_kv_production"
preview_id = "rate_limiter_kv_production_preview"

[[env.production.d1_databases]]
binding = "DB"
database_name = "com2000-db-production"
database_id = "com2000_db_production_id"

[[env.production.r2_buckets]]
binding = "ASSETS"
bucket_name = "com2000-assets-production"
preview_bucket_name = "com2000-assets-production-preview"

# Build configuration
# [build]
# command = "npm run build"
# watch_dir = "src"

# Development configuration
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"
upstream_protocol = "https"

# Miniflare configuration for local development
# [miniflare]
# kv_persist = true
# d1_persist = true
# r2_persist = true
# cache_persist = true

# Limits and quotas (disabled for Free plan)
# [limits]
# cpu_ms = 50
# memory_mb = 128

# Placement configuration
[placement]
mode = "smart"